"""Writes server/supabase/migrations/0002_market_config.sql from data/items.json and
data/market.json, so the server checks items with the same rules as the game.

    python3 tools/market/seed_catalog.py

Run it again (and apply the new migration) whenever items.json or market.json changes.
"""
import json
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))


def main():
    items = json.load(open(os.path.join(ROOT, "data", "items.json"), encoding="utf-8"))
    market = json.load(open(os.path.join(ROOT, "data", "market.json"), encoding="utf-8"))
    keep = ("slot", "class", "rarity", "unique", "main", "drop_only")
    catalog = {
        "bases": {k: {f: v[f] for f in keep if f in v} for k, v in items["bases"].items()},
        "rarities": {k: {f: v[f] for f in ("mult", "affixes", "boss_only") if f in v} for k, v in items["rarities"].items()},
        "rarity_order": items["rarity_order"],
        "affixes": {k: {f: v[f] for f in ("range", "scales") if f in v} for k, v in items["affixes"].items()},
        "level_growth": items["level_growth"],
        "max_upgrade": items["max_upgrade"],
    }
    server_market = {k: v for k, v in market.items() if k not in ("offline", "trader_names")}
    server_market.setdefault("max_item_level", 20)
    out = os.path.join(ROOT, "server", "supabase", "migrations", "0002_market_config.sql")

    def lit(obj):
        return "'" + json.dumps(obj, ensure_ascii=False, sort_keys=True).replace("'", "''") + "'::jsonb"

    with open(out, "w", encoding="utf-8") as f:
        f.write("-- Generated by tools/market/seed_catalog.py from data/items.json and data/market.json. Do not edit.\n")
        for key, value in (("items", catalog), ("market", server_market)):
            f.write(f"insert into public.market_config (key, value) values ('{key}', {lit(value)})\n"
                    f"  on conflict (key) do update set value = excluded.value;\n")
    print("wrote", os.path.relpath(out, ROOT))


if __name__ == "__main__":
    main()
